
import java.awt.Color;
import javax.swing.JFrame;

/**
 * Classe che disegna un frame con all'interno 4 bottoni ai lati (top, right,
 * bottom, left) e un panel centrale in cui viene disegnato un triangolo.
 * Cliccando i bottoni si sposta il triangolo nella direzione indicata.
 *
 * @author Bryan Beffa
 * @version 1.10.2018
 */
public class TriangleFrameApp extends JFrame {

    /**
     * Creates new form TriangleFrameApp
     */
    public TriangleFrameApp(int triangleSide, String title) {
        initComponents();

        //setto il titolo del frame
        setTitle(title);

        //setto il colore del background del triangolo e centro il triangolo
        myTrianglePanel.setColor(Color.green);
        myTrianglePanel.center();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        canvasJPanel = new javax.swing.JPanel();
        myTrianglePanel = new MyTrianglePanel();
        rightButton = new javax.swing.JButton();
        bottomButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topButton.setText("Top");
        topButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topButtonMouseClicked(evt);
            }
        });
        getContentPane().add(topButton, java.awt.BorderLayout.PAGE_START);

        leftButton.setText("Left");
        leftButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftButtonMouseClicked(evt);
            }
        });
        getContentPane().add(leftButton, java.awt.BorderLayout.LINE_START);

        canvasJPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout myTrianglePanelLayout = new javax.swing.GroupLayout(myTrianglePanel);
        myTrianglePanel.setLayout(myTrianglePanelLayout);
        myTrianglePanelLayout.setHorizontalGroup(
            myTrianglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );
        myTrianglePanelLayout.setVerticalGroup(
            myTrianglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        canvasJPanel.add(myTrianglePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(canvasJPanel, java.awt.BorderLayout.CENTER);

        rightButton.setText("Right");
        rightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightButtonMouseClicked(evt);
            }
        });
        getContentPane().add(rightButton, java.awt.BorderLayout.LINE_END);

        bottomButton.setText("Bottom");
        bottomButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottomButtonMouseClicked(evt);
            }
        });
        getContentPane().add(bottomButton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftButtonMouseClicked
        myTrianglePanel.moveToLeft();
    }//GEN-LAST:event_leftButtonMouseClicked

    private void rightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightButtonMouseClicked
        myTrianglePanel.moveToRight();
    }//GEN-LAST:event_rightButtonMouseClicked

    private void topButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topButtonMouseClicked
        myTrianglePanel.moveToTop();
    }//GEN-LAST:event_topButtonMouseClicked

    private void bottomButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottomButtonMouseClicked
        myTrianglePanel.moveToBottom();
    }//GEN-LAST:event_bottomButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriangleFrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriangleFrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriangleFrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriangleFrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriangleFrameApp(100, "Triangle Frame").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottomButton;
    private javax.swing.JPanel canvasJPanel;
    private javax.swing.JButton leftButton;
    private MyTrianglePanel myTrianglePanel;
    private javax.swing.JButton rightButton;
    private javax.swing.JButton topButton;
    // End of variables declaration//GEN-END:variables
}
