
/**
 * Classe che disegna un frame con al centro una griglia.
 * Ci sono bottoni nella parte alta per gestire il numero di colonne.
 * Ci sono bottoni nella parte destra per gestire il numero di righe.
 * Ci sono bottoni nella parte bassa per gestire il margine della griglia.
 *
 * @author Bryan Beffa
 * @version 04.10.2018
 */
public class GridFrame extends javax.swing.JFrame {

    /**
     * Creates new form GridFrame
     */
    public GridFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topButtonsPanel = new javax.swing.JPanel();
        addColsButton = new javax.swing.JButton();
        removeColsButton = new javax.swing.JButton();
        gridPanel = new javax.swing.JPanel();
        drawGrid = new DrawGrid();
        rightButtonsPanel = new javax.swing.JPanel();
        addRowsButton = new javax.swing.JButton();
        removeRowsButton = new javax.swing.JButton();
        bottomButtonsPanel = new javax.swing.JPanel();
        addMarginButton = new javax.swing.JButton();
        removeMarginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topButtonsPanel.setLayout(new java.awt.GridLayout());

        addColsButton.setText("+");
        addColsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addColsButtonMouseClicked(evt);
            }
        });
        topButtonsPanel.add(addColsButton);

        removeColsButton.setText("-");
        removeColsButton.setToolTipText("");
        removeColsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeColsButtonMouseClicked(evt);
            }
        });
        topButtonsPanel.add(removeColsButton);

        getContentPane().add(topButtonsPanel, java.awt.BorderLayout.PAGE_START);

        gridPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout drawGridLayout = new javax.swing.GroupLayout(drawGrid);
        drawGrid.setLayout(drawGridLayout);
        drawGridLayout.setHorizontalGroup(
            drawGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        drawGridLayout.setVerticalGroup(
            drawGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        gridPanel.add(drawGrid, java.awt.BorderLayout.CENTER);

        getContentPane().add(gridPanel, java.awt.BorderLayout.CENTER);

        rightButtonsPanel.setLayout(new java.awt.GridLayout(2, 0));

        addRowsButton.setText("+");
        addRowsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRowsButtonMouseClicked(evt);
            }
        });
        rightButtonsPanel.add(addRowsButton);

        removeRowsButton.setText("-");
        removeRowsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeRowsButtonMouseClicked(evt);
            }
        });
        rightButtonsPanel.add(removeRowsButton);

        getContentPane().add(rightButtonsPanel, java.awt.BorderLayout.LINE_END);

        bottomButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addMarginButton.setText("+");
        addMarginButton.setAlignmentY(0.0F);
        addMarginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMarginButtonMouseClicked(evt);
            }
        });
        bottomButtonsPanel.add(addMarginButton);

        removeMarginButton.setText("-");
        removeMarginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMarginButtonMouseClicked(evt);
            }
        });
        bottomButtonsPanel.add(removeMarginButton);

        getContentPane().add(bottomButtonsPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addColsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addColsButtonMouseClicked
        //aggiungo una colonna
        drawGrid.addCols();
    }//GEN-LAST:event_addColsButtonMouseClicked

    private void removeColsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeColsButtonMouseClicked
        //rimuovo una colonna
        drawGrid.removeCols();
    }//GEN-LAST:event_removeColsButtonMouseClicked

    private void addRowsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRowsButtonMouseClicked
        //aggiungo una riga
        drawGrid.addRows();
    }//GEN-LAST:event_addRowsButtonMouseClicked

    private void removeRowsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeRowsButtonMouseClicked
        //rimuovo una riga
        drawGrid.removeRows();
    }//GEN-LAST:event_removeRowsButtonMouseClicked

    private void addMarginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMarginButtonMouseClicked
        //aggiungo il margine 
        drawGrid.addMargin();
    }//GEN-LAST:event_addMarginButtonMouseClicked

    private void removeMarginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMarginButtonMouseClicked
        //rimuovo il margine
        drawGrid.removeMargin();
    }//GEN-LAST:event_removeMarginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GridFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addColsButton;
    private javax.swing.JButton addMarginButton;
    private javax.swing.JButton addRowsButton;
    private javax.swing.JPanel bottomButtonsPanel;
    private DrawGrid drawGrid;
    private javax.swing.JPanel gridPanel;
    private javax.swing.JButton removeColsButton;
    private javax.swing.JButton removeMarginButton;
    private javax.swing.JButton removeRowsButton;
    private javax.swing.JPanel rightButtonsPanel;
    private javax.swing.JPanel topButtonsPanel;
    // End of variables declaration//GEN-END:variables
}
